### ISSUE TITLE
Error on connection?

### ISSUE THREAD

**Issue by karzak** [ItayTsabary/BitcoinMempoolSampler#1]
When I run sample_mempool.py, the config looks correct, but I get the following error. 
```
Traceback (most recent call last):
  File "sample_mempool.py", line 223, in <module>
    main(config)
  File "sample_mempool.py", line 149, in main
    blockCount = bitcoinCoreConnection.getblockcount()
  File "/Users/kjd/python_code/bitcoin/BitcoinMempoolSampler/bitcoinrpc/connection.py", line 90, in getblockcount
    return self.proxy.getblockcount()
  File "/Users/kjd/python_code/bitcoin/BitcoinMempoolSampler/bitcoinrpc/proxy.py", line 130, in __call__
    resp = json.loads(resp, parse_float=decimal.Decimal)
  File "/Users/kjd/anaconda3/envs/bitcoin-mempool/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/Users/kjd/anaconda3/envs/bitcoin-mempool/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/kjd/anaconda3/envs/bitcoin-mempool/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

When I print config
```
(u'RPCUSER', u'RPCPASS', u'52.55.70.13', u'8332')
```

My bitcoin.conf looks like 

```
feefilter=0
maxmempool=1000
mempoolexpiry=336
txindex=1
limitancestorcount=500
limitancestorsize=500
limitdescendantcount=500
limitdescendantsize=500
logips=1
logtimestamps=0
logtimemicros=1
printpriority=1
rpcuser=RPCUSER
rpcpass=RPCPASS
rpcport=8332
server=1
externalip=52.55.70.13
daemon=1
dbcache=2048
listen=1
rpcallowip=127.0.0.1
datadir=/media/data/.bitcoin
```

Do you see any obvious issues?

**Comment by karzak** [comment]
There were two bugs in the bitcoin.conf:
`rpcpass` -> `rpcpassword` and
`rpcallowip=0.0.0.0/0` fixed my issues.

**Comment by ItayTsabary** [comment]
Great, thanks for debugging this!

I added an example of a bitcoin.conf file, the field name is indeed _rpcpassword_.

The _rpcallowip_ field was set to 127.0.0.1 - I believe this is _localhost_. If you are running the script on one host and the node on another you probably need to provide the specific node's ip or use 0.0.0.0/0 that translates to _all_.
